<?php
$z[0]=Array("global","",379,406);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",476,503);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",506,532);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",685,711);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>About us</span></a></li>\r\n          ",851,988);
$z[4][4]['typeid']="1";
$z[5]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Achievement</span></a></li>\r\n          ",1000,1140);
$z[5][4]['typeid']="5";
$z[6]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>News</span></a></li>\r\n          ",1152,1285);
$z[6][4]['typeid']="9";
$z[7]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Knowledge</span></a></li>\r\n          ",1297,1436);
$z[7][4]['typeid']="12";
$z[8]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Services</span></a></li>\r\n          ",1448,1586);
$z[8][4]['typeid']="14";
$z[9]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Contact</span></a></li>\r\n          ",1598,1735);
$z[9][4]['typeid']="17";

?>