<?php
$z[0]=Array("global","",373,400);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",470,497);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",500,526);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",679,705);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>About us</span></a></li>\r\n          ",846,983);
$z[4][4]['typeid']="1";
$z[5]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Achievement</span></a></li>\r\n          ",995,1135);
$z[5][4]['typeid']="5";
$z[6]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>News</span></a></li>\r\n          ",1147,1280);
$z[6][4]['typeid']="9";
$z[7]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Knowledge</span></a></li>\r\n          ",1292,1431);
$z[7][4]['typeid']="12";
$z[8]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Services</span></a></li>\r\n          ",1443,1581);
$z[8][4]['typeid']="14";
$z[9]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Contact</span></a></li>\r\n          ",1593,1730);
$z[9][4]['typeid']="17";

?>